### ISSUE TITLE
Unable to find the correct COM port (automatically)

### ISSUE THREAD

**Issue by gipfeli** [rirze/py-mirobot#13]
[http://discuz.wlkata.com/forum.php?mod=viewthread&tid=298&page=2#pid479](url)

Taken from the WLkata forum. 

So far the COM port have to be specified as following, so that the Mirobot can be connected and controlled:

`portname='/dev/ttySX'
`
With `X` is number of COM-Port (i.e `COM3 => /dev/ttyS3`)

Without specifying portname:

`Exception has occurred: MirobotAmbiguousPort
Unable to determine which port to automatically connect to!
Found these ports: ['/dev/ttyS0', '/dev/ttyS1', '/dev/ttyS10', '/dev/ttyS100', '/dev/ttyS101', '/dev/ttyS102', '/dev/ttyS103', '/dev/ttyS104', '/dev/ttyS105', '/dev/ttyS106', '/dev/ttyS107', '/dev/ttyS108', '/dev/ttyS109', '/dev/ttyS11', '/dev/ttyS110', '/dev/ttyS111', '/dev/ttyS112', '/dev/ttyS113', '/dev/ttyS114', '/dev/ttyS115', '/dev/ttyS116', '/dev/ttyS117', '/dev/ttyS118', '/dev/ttyS119', '/dev/ttyS12', '/dev/ttyS120', '/dev/ttyS121', '/dev/ttyS122', '/dev/ttyS123', '/dev/ttyS124', '/dev/ttyS125', '/dev/ttyS126', '/dev/ttyS127', '/dev/ttyS128', '/dev/ttyS129', '/dev/ttyS13', '/dev/ttyS130', '/dev/ttyS131', '/dev/ttyS132', '/dev/ttyS133', '/dev/ttyS134', '/dev/ttyS135', '/dev/ttyS136', '/dev/ttyS137', '/dev/ttyS138', '/dev/ttyS139', '/dev/ttyS14', '/dev/ttyS140', '/dev/ttyS141', '/dev/ttyS142', '/dev/ttyS143', '/dev/ttyS144', '/dev/ttyS145', '/dev/ttyS146', '/dev/ttyS147', '/dev/ttyS148', '/dev/ttyS149', '/dev/ttyS15', '/dev/ttyS150', '/dev/ttyS151', '/dev/ttyS152', '/dev/ttyS153', '/dev/ttyS154', '/dev/ttyS155', '/dev/ttyS156', '/dev/ttyS157', '/dev/ttyS158', '/dev/ttyS159', '/dev/ttyS16', '/dev/ttyS160', '/dev/ttyS161', '/dev/ttyS162', '/dev/ttyS163', '/dev/ttyS164', '/dev/ttyS165', '/dev/ttyS166', '/dev/ttyS167', '/dev/ttyS168', '/dev/ttyS169', '/dev/ttyS17', '/dev/ttyS170', '/dev/ttyS171', '/dev/ttyS172', '/dev/ttyS173', '/dev/ttyS174', '/dev/ttyS175', '/dev/ttyS176', '/dev/ttyS177', '/dev/ttyS178', '/dev/ttyS179', '/dev/ttyS18', '/dev/ttyS180', '/dev/ttyS181', '/dev/ttyS182', '/dev/ttyS183', '/dev/ttyS184', '/dev/ttyS185', '/dev/ttyS186', '/dev/ttyS187', '/dev/ttyS188', '/dev/ttyS189', '/dev/ttyS19', '/dev/ttyS190', '/dev/ttyS191', '/dev/ttyS2', '/dev/ttyS20', '/dev/ttyS21', '/dev/ttyS22', '/dev/ttyS23', '/dev/ttyS24', '/dev/ttyS25', '/dev/ttyS26', '/dev/ttyS27', '/dev/ttyS28', '/dev/ttyS29', '/dev/ttyS3', '/dev/ttyS30', '/dev/ttyS31', '/dev/ttyS32', '/dev/ttyS33', '/dev/ttyS34', '/dev/ttyS35', '/dev/ttyS36', '/dev/ttyS37', '/dev/ttyS38', '/dev/ttyS39', '/dev/ttyS4', '/dev/ttyS40', '/dev/ttyS41', '/dev/ttyS42', '/dev/ttyS43', '/dev/ttyS44', '/dev/ttyS45', '/dev/ttyS46', '/dev/ttyS47', '/dev/ttyS48', '/dev/ttyS49', '/dev/ttyS5', '/dev/ttyS50', '/dev/ttyS51', '/dev/ttyS52', '/dev/ttyS53', '/dev/ttyS54', '/dev/ttyS55', '/dev/ttyS56', '/dev/ttyS57', '/dev/ttyS58', '/dev/ttyS59', '/dev/ttyS6', '/dev/ttyS60', '/dev/ttyS61', '/dev/ttyS62', '/dev/ttyS63', '/dev/ttyS64', '/dev/ttyS65', '/dev/ttyS66', '/dev/ttyS67', '/dev/ttyS68', '/dev/ttyS69', '/dev/ttyS7', '/dev/ttyS70', '/dev/ttyS71', '/dev/ttyS72', '/dev/ttyS73', '/dev/ttyS74', '/dev/ttyS75', '/dev/ttyS76', '/dev/ttyS77', '/dev/ttyS78', '/dev/ttyS79', '/dev/ttyS8', '/dev/ttyS80', '/dev/ttyS81', '/dev/ttyS82', '/dev/ttyS83', '/dev/ttyS84', '/dev/ttyS85', '/dev/ttyS86', '/dev/ttyS87', '/dev/ttyS88', '/dev/ttyS89', '/dev/ttyS9', '/dev/ttyS90', '/dev/ttyS91', '/dev/ttyS92', '/dev/ttyS93', '/dev/ttyS94', '/dev/ttyS95', '/dev/ttyS96', '/dev/ttyS97', '/dev/ttyS98', '/dev/ttyS99'].
To fix this, please provide port name explicitly.
  File "/home/gipfeli/DevProg/RobotArm/testArm.py", line 3, in <module>
    with Mirobot() as m:`

**Comment by rirze** [comment]
Thanks for the report.

I've recently starting testing the library on a Windows machine, will try and see if I can make the current code work on WSL automagically.

**Comment by rirze** [comment]
Good news, the new `autofindport` function logic finds available ports automatically on WSL. You shouldn't need to specify portname explicitly in the next release. Gonna close this for now-- feel free to reopen if upgrading your version of the library doesn't work in the near future. (Or feel free to test it out by downloading from the git repository directly)
