### ISSUE TITLE
Mirobot stop on m.home_simultaneous()

### ISSUE THREAD

**Issue by river-chang** [rirze/py-mirobot#19]
I run my Mirobot with the Example codes below:

# !/usr/bin/env python3
from mirobot import Mirobot

# Default for `wait=` is `True`, but explicitly state it here to showcase this.
with Mirobot(portname='COM12', debug=True) as m:
    # Mirobot will by default wait for any command because we specified `wait=True` for the class above.
    m.home_simultaneous()

    # print our dataclass maintained by Mirobot. Shows the x,y,z,a,b,c coordinates.
    print(m.cartesian)

    # increment arm's position using a for-loop
    for count in range(5):
        mx = 180.00
        my = 0.00 + count * 5
        mz = 170 + count * 5

        print(f"************Count {count}************")

        # notice how we don't need any "wait" or "sleep" commands!
        # the following command will only return when the Mirobot returns 'Ok' and when Mirobot is 'Idle'
        m.go_to_cartesian_ptp(mx, my, mz)

        # print our cartesian coordinates again
        print(m.cartesian)

than, the robotic arm started to move. After moving it stopped in zero position.
the debug code is shown below:

(base) C:\Users\user\Desktop>python 123.py
[] [DEBUG] Attempting to open serial port COM12
[] [DEBUG] Succeeded in opening serial port COM12
[COM12] [DEBUG] [RECV]
[COM12] [DEBUG] [RECV] Grbl 0.9j ['$' for help]
[COM12] [DEBUG] [RECV]
[COM12] [DEBUG] [RECV] Qinnew Robot 20201126 based on Grbl 0.9j ['$' for help]
[COM12] [DEBUG] [RECV]
[COM12] [DEBUG] [RECV] D1: 127.000
[COM12] [DEBUG] [RECV] A1: 29.690
[COM12] [DEBUG] [RECV] A2: 108.000
[COM12] [DEBUG] [RECV] A3: 20.000
[COM12] [DEBUG] [RECV] D4: 168.980
[COM12] [DEBUG] [RECV] L: -24.280
[COM12] [DEBUG] [RECV] X offset: 0.000
[COM12] [DEBUG] [RECV] Y offset: 0.000
[COM12] [DEBUG] [RECV] Z offset: 0.000
[COM12] [DEBUG] [RECV] X tool frame offset: 0.000
[COM12] [DEBUG] [RECV] Y tool frame offset: 0.000
[COM12] [DEBUG] [RECV] Z tool frame offset: 0.000
[COM12] [DEBUG] [RECV] Line discard number: 0
[COM12] [DEBUG] [RECV] Axis_7 mode: Rail mode
[COM12] [DEBUG] [RECV] Initialized Cartesian coordinates and rotation:
[COM12] [DEBUG] [RECV] X: 198.670
[COM12] [DEBUG] [RECV] Y: 0.000
[COM12] [DEBUG] [RECV] Z: 230.720
[COM12] [DEBUG] [RECV] RX: 0.000
[COM12] [DEBUG] [RECV] RY: 0.000
[COM12] [DEBUG] [RECV] RZ: 0.000
[COM12] [DEBUG] [RECV] Using reset pos!
[COM12] [DEBUG] [SENT] $H
[COM12] [DEBUG] [RECV]
[COM12] [DEBUG] [RECV] Free memory: 2355
[COM12] [DEBUG] [RECV] Info, in homeing moving...ok

It seems Mirobot stopped on the code "m.home_simultaneous()"
How do Mirobot run the next instruction "print(m.cartesian)......."? 
I am a junior Python learner.
Thanks everyone.

**Comment by rirze** [comment]
You're on a newer firmware. WLKata refuses to open-source their firmware so I cannot (and refuse) to reverse engineer their API output. 

Last I developed on this library, it was guaranteed to work with firmware version `20191228_2`. 

If you really want to get support, I'd recommend filing the same issue at WLKata's bastardized fork of my library: https://github.com/wlkata/mirobot-py

**Comment by river-chang** [comment]
Thanks for your kind rirze.
Do you know where to download the firmware 20191228_2?

**Comment by river-chang** [comment]
By the way. I will try the other version Python module and response the result.(such as latest or 2.0 beta)

**Comment by rirze** [comment]
The firmware used to be available, but is now closed off somewhere. I could scavenge through my clone history for source folder, which you could use to build yourself and flash onto the mirobot. Leave your email and I'll eventually get around to it. 

Careful with using WKLata's releases for `mirobot-py`, they simply forked my versions and never bothered to update any release packages after they made their changes. To install their package, you'll have to clone the repository and then do a `pip3 install -e .`. 

Good luck.

**Comment by river-chang** [comment]
Thank you rirze.
My Mirobot was just bought last December. The installed firmware is 20201126. 
My email is 
river@jres.tc.edu.tw

Again, thank you very much.
